In [1]:
import pandas as pd
from datetime import datetime
import yfinance as yf

In [2]:
df_apple = yf.download('AAPL', pd.to_datetime('01/01/2015'), pd.to_datetime(datetime.today()))
df_apple['stock'] = 'AAPL'
df_apple = df_apple.set_axis(['Close', 'High', 'Low', 'Open', 'Volume','stock'], axis=1)

[*********************100%***********************]  1 of 1 completed

In [3]:
df_tesla = yf.download('TSLA', pd.to_datetime('01/01/2015'), pd.to_datetime(datetime.today()))
df_tesla['stock'] = 'TSLA'
df_tesla = df_tesla.set_axis(['Close', 'High', 'Low', 'Open', 'Volume','stock'], axis=1)

[*********************100%***********************]  1 of 1 completed

In [4]:
df_ibm = yf.download('IBM', pd.to_datetime('01/01/2015'), pd.to_datetime(datetime.today()))
df_ibm['stock'] = 'IBM'
df_ibm = df_ibm.set_axis(['Close', 'High', 'Low', 'Open', 'Volume','stock'], axis=1)

[*********************100%***********************]  1 of 1 completed

In [5]:
df_mfst = yf.download('MSFT', pd.to_datetime('01/01/2015'), pd.to_datetime(datetime.today()))
df_mfst['stock'] = 'MFST'
df_mfst = df_mfst.set_axis(['Close', 'High', 'Low', 'Open', 'Volume','stock'], axis=1)

[*********************100%***********************]  1 of 1 completed

In [6]:
#step 7
df = pd.concat([df_apple, df_tesla, df_ibm, df_mfst]).sort_values('Date')
df

                 Close        High         Low        Open     Volume stock
Date
2015-01-02   24.171755   24.638255   23.733996   24.627199  212818400  AAPL
2015-01-02   14.620667   14.883333   14.217333   14.858000   71466000  TSLA
2015-01-02   39.607182   40.166222   39.420837   39.522480   27913900  MFST
2015-01-02   96.164108   96.905846   95.535121   95.719073    5779673   IBM
2015-01-05   39.242973   39.581784   39.175209   39.276852   39673900  MFST
...                ...         ...         ...         ...        ...   ...
2026-08-28  319.700012  322.369995  315.450012  316.850006   38609800  AAPL
2026-08-31  363.839996  367.149994  347.149994  347.149994   29257740  TSLA
2026-08-31  314.100006  321.234985  314.014496  319.559998   11320225  AAPL
2026-08-31  234.309998  235.600006  232.179993  232.729996    1272095   IBM
2026-08-31  509.734985  512.190002  507.309998  510.325012    7058865  MFST

[11728 rows x 6 columns]

In [7]:
#step 8
df.set_index([df.index,'stock'], inplace=True)
df

                       Close        High         Low        Open     Volume
Date       stock
2015-01-02 AAPL    24.171755   24.638255   23.733996   24.627199  212818400
           TSLA    14.620667   14.883333   14.217333   14.858000   71466000
           MFST    39.607182   40.166222   39.420837   39.522480   27913900
           IBM     96.164108   96.905846   95.535121   95.719073    5779673
2015-01-05 MFST    39.242973   39.581784   39.175209   39.276852   39673900
...                      ...         ...         ...         ...        ...
2026-08-28 AAPL   319.700012  322.369995  315.450012  316.850006   38609800
2026-08-31 TSLA   363.839996  367.149994  347.149994  347.149994   29257740
           AAPL   314.100006  321.234985  314.014496  319.559998   11320225
           IBM    234.309998  235.600006  232.179993  232.729996    1272095
           MFST   509.734985  512.190002  507.309998  510.325012    7058865

[11728 rows x 5 columns]

In [12]:
#step 9
vol = df['Volume']

In [25]:
#step 10
vol.unstack().groupby(pd.Grouper(freq='W')).sum()

stock             AAPL       IBM       MFST       TSLA
Date
2015-01-04   212818400   5779673   27913900   71466000
2015-01-11  1133010000  25578884  158825300  340644000
2015-01-18  1216906400  24329751  157088200  461988000
2015-01-25   794948000  32682062  137352600  243175500
2015-02-01  1863370800  34442689  437786800  235803000
...                ...       ...        ...        ...
2026-08-09   273068900  30252900  215894200  164946600
2026-08-16   192525700  27432800  122514000  157193300
2026-08-23   229935400  26432600  116216900  180757400
2026-08-30   165596900  21177700  115375800  160629700
2026-09-06    11320225   1272095    7058865   29257740

[610 rows x 4 columns]

In [26]:
#step 10 v2
vol.unstack().resample('W').sum()

stock             AAPL       IBM       MFST       TSLA
Date
2015-01-04   212818400   5779673   27913900   71466000
2015-01-11  1133010000  25578884  158825300  340644000
2015-01-18  1216906400  24329751  157088200  461988000
2015-01-25   794948000  32682062  137352600  243175500
2015-02-01  1863370800  34442689  437786800  235803000
...                ...       ...        ...        ...
2026-08-09   273068900  30252900  215894200  164946600
2026-08-16   192525700  27432800  122514000  157193300
2026-08-23   229935400  26432600  116216900  180757400
2026-08-30   165596900  21177700  115375800  160629700
2026-09-06    11320225   1272095    7058865   29257740

[610 rows x 4 columns]

In [52]:
df_vol = vol.unstack()

df_vol.groupby([
    df_vol.index.year.rename('year'),
    df_vol.index.isocalendar().week.rename('week')
]).sum()

stock            AAPL       IBM       MFST       TSLA
year week
2015 1      212818400   5779673   27913900   71466000
     2     1133010000  25578884  158825300  340644000
     3     1216906400  24329751  157088200  461988000
     4      794948000  32682062  137352600  243175500
     5     1863370800  34442689  437786800  235803000
...               ...       ...        ...        ...
2026 32     273068900  30252900  215894200  164946600
     33     192525700  27432800  122514000  157193300
     34     229935400  26432600  116216900  180757400
     35     165596900  21177700  115375800  160629700
     36      11320225   1272095    7058865   29257740

[610 rows x 4 columns]

In [84]:
yr_2015 = vol.unstack()
yr_2015.groupby(yr_2015.index.year).sum().head(1)

stock         AAPL         IBM        MFST         TSLA
Date
2015   52264199600  1156439400  9059455900  16323267000