In [1]:
import pandas as pd
from random import randint

In [2]:
#step2
sr1 = [randint(1,4) for i in range(100)]
sr2 = [randint(1,3) for i in range(100)]
sr3 = [randint(10000,30000) for i in range(100)]

In [3]:
pdsr1 = pd.Series(sr1)
pdsr2 = pd.Series(sr2)
pdsr3 = pd.Series(sr3)

In [4]:
# df = pd.DataFrame({'bedrs':pdsr1, 'bathrs':pdsr2, 'price_sqr_meter':pdsr3})

In [10]:
#step 3
df = pd.concat([pdsr1,pdsr2,pdsr3], axis=1)
df

    0  1      2
0   1  1  23493
1   3  2  16968
2   3  1  17135
3   1  1  18950
4   2  3  11734
.. .. ..    ...
95  3  2  20123
96  4  2  19072
97  2  2  27986
98  1  1  17007
99  4  3  16726

[100 rows x 3 columns]

In [11]:
#step 4
df.rename({
    0:'bedrs',
    1:'bathrs',
    2:'price_sqr_meter'
}, inplace=True, axis=1)
df

    bedrs  bathrs  price_sqr_meter
0       1       1            23493
1       3       2            16968
2       3       1            17135
3       1       1            18950
4       2       3            11734
..    ...     ...              ...
95      3       2            20123
96      4       2            19072
97      2       2            27986
98      1       1            17007
99      4       3            16726

[100 rows x 3 columns]

In [17]:
#step 5
bigcolumn = pd.concat([pdsr1, pdsr2, pdsr3], ignore_index=True)
bigcolumn = bigcolumn.to_frame()
bigcolumn

         0
0        1
1        3
2        3
3        1
4        2
..     ...
295  20123
296  19072
297  27986
298  17007
299  16726

[300 rows x 1 columns]