In [1]:
import pandas as pd

In [2]:
pokemon = {
    'evolution': ['Ivysaur','Charmeleon','Wartortle','Metapod'],
    'hp': [45,39,44,45],
    'name' : ['Bulbasaur','Charmander','Squirtle','Caterpie'],
    'pokedex': ['yes','no','yes','no'],
    'type': ['Grass','Fire','Water','Bug']
}

In [5]:
df = pd.DataFrame(pokemon)
df

    evolution  hp        name pokedex   type
0     Ivysaur  45   Bulbasaur     yes  Grass
1  Charmeleon  39  Charmander      no   Fire
2   Wartortle  44    Squirtle     yes  Water
3     Metapod  45    Caterpie      no    Bug

In [8]:
df = df.loc[:,['name','type','hp','evolution','pokedex']]
df

         name   type  hp   evolution pokedex
0   Bulbasaur  Grass  45     Ivysaur     yes
1  Charmander   Fire  39  Charmeleon      no
2    Squirtle  Water  44   Wartortle     yes
3    Caterpie    Bug  45     Metapod      no

In [11]:
place = [2,1,3,4]
df['place'] = place
df

         name   type  hp   evolution pokedex  place
0   Bulbasaur  Grass  45     Ivysaur     yes      2
1  Charmander   Fire  39  Charmeleon      no      1
2    Squirtle  Water  44   Wartortle     yes      3
3    Caterpie    Bug  45     Metapod      no      4

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       4 non-null      str
 1   type       4 non-null      str
 2   hp         4 non-null      int64
 3   evolution  4 non-null      str
 4   pokedex    4 non-null      str
 5   place      4 non-null      int64
dtypes: int64(2), str(4)
memory usage: 324.0 bytes

In [20]:
df.loc[(df.hp == df.hp.max())]

        name   type  hp evolution pokedex  place
0  Bulbasaur  Grass  45   Ivysaur     yes      2
3   Caterpie    Bug  45   Metapod      no      4